# novoface.spec — PyInstaller build spec
#
# Build (CPU-only, no OpenVINO):
#   pip install pyinstaller pywebview platformdirs
#   pyinstaller novoface.spec
#
# Build (with Intel GPU support):
#   pip install pyinstaller pywebview platformdirs openvino
#   pyinstaller novoface.spec
#
# Output: dist/novoface/novoface.exe  (--onedir, no console window)
#
# Notes:
# - insightface and onnxruntime ship native DLLs that PyInstaller needs help
#   collecting; collect_all() handles that automatically.
# - openvino is collected only when installed in the build environment.
#   If absent, the GPU option is silently hidden in the first-run dialog.
# - pywebview on Windows uses WebView2 (Edge), which is pre-installed on all
#   Windows 10/11 machines since ~2021.  No extra runtime bundling required.
# - The face_review_ui.html is included as a data file in the bundle root so
#   that app.py's _base_dir() / "face_review_ui.html" resolves correctly.
# - OpenVINO models (~262 MB) are NOT bundled — they are downloaded at first
#   run when the user enables GPU acceleration in the setup dialog.

import sys as _sys
_sys.path.insert(0, '.')
from version import __version__, _version_tuple  # noqa: E402

from PyInstaller.utils.hooks import collect_all, collect_submodules

block_cipher = None

# ── Collect data + binaries from packages that need it ───────────────────────
ins_datas, ins_binaries, ins_hidden = collect_all("insightface")
ort_datas, ort_binaries, ort_hidden = collect_all("onnxruntime")
wv_datas,  wv_binaries,  wv_hidden  = collect_all("webview")

# OpenVINO: collected only when installed in the build environment.
# GPU acceleration is silently unavailable in the app if openvino is absent.
try:
    ov_datas, ov_binaries, ov_hidden = collect_all("openvino")
except Exception:
    ov_datas, ov_binaries, ov_hidden = [], [], []

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=ins_binaries + ort_binaries + wv_binaries + ov_binaries,
    datas=[
        # App resources
        ("face_review_ui.html", "."),
        ("face_scan.py",        "."),
        ("openvino_pipeline.py",".",),
        ("app.py",              "."),
        ("version.py",          "."),
    ] + ins_datas + ort_datas + wv_datas + ov_datas,
    hiddenimports=[
        # pywebview Windows backend
        "webview.platforms.winforms",
        # Flask internals sometimes missed
        "flask",
        "flask.templating",
        "jinja2",
        "werkzeug",
        "werkzeug.serving",
        # Common missed imports
        "pkg_resources",
        "pkg_resources.py2_compat",
        "platformdirs",
        "sklearn.utils._cython_blas",
        "sklearn.neighbors.typedefs",
        "sklearn.neighbors.quad_tree",
        "sklearn.tree._utils",
        # OpenVINO internals (no-op if not installed)
        "openvino.runtime",
        "openvino._pyopenvino",
    ] + ins_hidden + ort_hidden + wv_hidden + ov_hidden
      + collect_submodules("sklearn"),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Keep bundle lean — these are never used at runtime
        "matplotlib",
        "IPython",
        "jupyter",
        "notebook",
        "pytest",
        "sphinx",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="novoface",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,      # No black console window
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version="installer/version_info.txt",   # Windows VERSIONINFO (generated by: python version.py)
    icon="installer/novoface.ico",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="novoface",
)
